# Site settings
title: Data Expedition Demolabs
url: https://dataexpedition.demokratielabore.de/

sass:
  sass_dir: css/_scss
  style: compressed

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: EEEEEE #d8b365
  primary-rgb: "39, 196, 244" #"216,179,101"
  secondary: 0A070C #B2230B
  secondary-dark: ff0033 #01665e

# Build settings
markdown: kramdown
permalink: pretty

